[package]
name = "hns-conformance"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish = false

[dependencies]
hns-covenants.workspace = true
hns-dns-relay-protocol.workspace = true
hns-header-consensus.workspace = true
hns-hnsr-protocol.workspace = true
hns-marketplace-protocol.workspace = true
hns-mining.workspace = true
hns-odoh-protocol.workspace = true
hns-p2p-experimental.workspace = true
hns-p2p-wire.workspace = true
hns-script.workspace = true
hns-service-authority.workspace = true
hns-swap.workspace = true
hns-transaction.workspace = true
hns-urkel-proof.workspace = true
thiserror.workspace = true

[dev-dependencies]
hex.workspace = true

[lints]
workspace = true
