[package]
name = "hns-encoding"
description = "Strict bounded binary encoding for Handshake wire protocols"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
documentation = "https://docs.rs/hns-encoding"
readme = "README.md"
keywords.workspace = true
categories.workspace = true
publish.workspace = true

[dependencies]
thiserror.workspace = true

[lints]
workspace = true
