[workspace]
members = [
    "crates/hns-dns-relay-protocol",
    "crates/hns-encoding",
    "crates/hns-p2p-experimental",
    "crates/hns-primitives",
    "generators/hns-registry-gen",
]
resolver = "3"

[workspace.package]
version = "0.1.0"
edition = "2024"
rust-version = "1.89"
license = "MIT OR Apache-2.0"
repository = "https://github.com/denuoweb/hns-rs"

[workspace.dependencies]
hex = "0.4.3"
serde = { version = "1.0.219", features = ["derive"] }
sha2 = "0.10.9"
thiserror = "2.0.12"
toml = "0.8.22"

[workspace.lints.rust]
unsafe_code = "forbid"

[workspace.lints.clippy]
all = "warn"
