[package]
name = "hns-script"
description = "Handshake script, signature hashing, and fee-policy primitives"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
documentation = "https://docs.rs/hns-script"
readme = "README.md"
keywords.workspace = true
categories.workspace = true
publish.workspace = true

[dependencies]
blake2.workspace = true
hns-encoding.workspace = true
hns-primitives.workspace = true
hns-transaction.workspace = true
k256.workspace = true
ripemd = "0.1.3"
sha1 = "0.10.6"
sha2.workspace = true
sha3.workspace = true
thiserror.workspace = true

[dev-dependencies]
hex.workspace = true
hns-covenants.workspace = true

[lints]
workspace = true
