[package]
name = "hns-transaction"
description = "Canonical Handshake transaction and witness encoding"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
documentation = "https://docs.rs/hns-transaction"
readme = "README.md"
keywords.workspace = true
categories.workspace = true
publish.workspace = true

[dependencies]
blake2.workspace = true
hns-covenants.workspace = true
hns-encoding.workspace = true
hns-primitives.workspace = true
thiserror.workspace = true

[dev-dependencies]
hex.workspace = true

[lints]
workspace = true
