[package]
name = "hns-hnsr-protocol"
description = "Draft HIP 78 Handshake rendezvous and authenticated relay protocol"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
blake2.workspace = true
hns-encoding = { path = "../hns-encoding" }
k256.workspace = true
thiserror.workspace = true
zeroize.workspace = true

[dev-dependencies]
hex.workspace = true

[lints]
workspace = true
