//! Direct fixed-terms HNS/BTC offers.
//!
//! A direct offer has no oracle dependency. It is a signed promise
//! to exchange one exact native amount for another exact native amount.  The
//! live board may display and aggregate those offers as price levels, but that
//! presentation is never settlement authority.

use hns_encoding::Decoder;

use crate::crypto;
use crate::types::encode_fixed_versioned;
use crate::{
    AssetAmount, AssetId, MarketPair, MarketplaceError, NetworkBinding, Result, SignedObjectHeader,
};

pub const MAX_DIRECT_OFFER_SIZE: usize = 8 * 1024;

const LEGACY_OFFER_ID_DOMAIN: &[u8] = b"HNS-DIRECT-OFFER-ID-V1\0";
const LEGACY_OFFER_SIGNATURE_DOMAIN: &[u8] = b"HNS-DIRECT-OFFER-SIGNATURE-V1\0";
const LEGACY_OFFER_CANCEL_SIGNATURE_DOMAIN: &[u8] = b"HNS-DIRECT-OFFER-CANCEL-V1\0";
const LEGACY_OFFER_TAKE_SIGNATURE_DOMAIN: &[u8] = b"HNS-DIRECT-OFFER-TAKE-V1\0";
const OFFER_ID_DOMAIN: &[u8] = b"HNS-DIRECT-OFFER-ID-V2\0";
const OFFER_SIGNATURE_DOMAIN: &[u8] = b"HNS-DIRECT-OFFER-SIGNATURE-V2\0";
const OFFER_CANCEL_SIGNATURE_DOMAIN: &[u8] = b"HNS-DIRECT-OFFER-CANCEL-V2\0";
const OFFER_ACCEPT_SIGNATURE_DOMAIN: &[u8] = b"HNS-DIRECT-OFFER-ACCEPT-V2\0";

/// Explicit role semantics for a direct offer and its response.
///
/// Version 1 incorrectly treated the public offer setter as the atomic-swap
/// maker. Version 2 keeps the public offer as a signed intent: the responding
/// participant initializes the executable swap as maker, and the offer setter
/// countersigns it as taker. The legacy value is decode-only compatibility for
/// recovery of already-countersigned sessions; current cross-chain envelopes
/// reject it.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
#[repr(u8)]
pub enum DirectOfferRoleModel {
    LegacyOfferSetterMaker = 1,
    OfferSetterTaker = 2,
}

impl DirectOfferRoleModel {
    fn decode_current(decoder: &mut Decoder<'_>) -> Result<Self> {
        match decoder.read_u8()? {
            2 => Ok(Self::OfferSetterTaker),
            _ => Err(MarketplaceError::Invalid(
                "unsupported direct-offer role model",
            )),
        }
    }

    pub const fn is_current(self) -> bool {
        matches!(self, Self::OfferSetterTaker)
    }
}

/// An offer setter's exact, indivisible HNS/BTC exchange intent.
///
/// `header.signer_public_key` is the offer setter's long-term marketplace
/// identity. `offer_setter_settlement_public_key` is the distinct settlement
/// authority the setter will use as the eventual atomic-swap taker. A peer who
/// accepts this intent becomes the protocol maker and proposes the executable
/// swap with the two asset sides reversed into the maker's perspective.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct DirectOffer {
    pub role_model: DirectOfferRoleModel,
    pub header: SignedObjectHeader,
    pub offer_id: [u8; 32],
    /// Offer-scoped session identity. The responding swap maker must repeat
    /// this exact value; it keeps the setter's precommitted taker key and all
    /// later HTLC messages in one immutable scope.
    pub swap_session_id: [u8; 32],
    pub offer_setter_settlement_public_key: [u8; 33],
    pub offered_asset: AssetId,
    pub offered_amount: AssetAmount,
    pub received_asset: AssetId,
    pub received_amount: AssetAmount,
    pub signature: [u8; 64],
}

impl DirectOffer {
    pub fn refresh_id(&mut self) -> Result<()> {
        self.offer_id = crypto::hash(self.id_domain(), &self.encode_unsigned()?);
        Ok(())
    }

    /// Sign the fixed terms with the offer setter's marketplace identity.
    /// The independent settlement key must already have been generated by the
    /// wallet and supplied in `offer_setter_settlement_public_key`.
    pub fn sign(&mut self, private_key: &[u8; 32]) -> Result<()> {
        bind_signer(&mut self.header, private_key)?;
        self.refresh_id()?;
        self.signature = crypto::sign(
            self.signature_domain(),
            &self.signature_bytes()?,
            &self.header.signer_public_key,
            private_key,
        )?;
        Ok(())
    }

    pub fn verify_at(&self, expected_network: NetworkBinding, now: u64) -> Result<()> {
        self.header.validate_at(expected_network, now)?;
        self.verify_id()?;
        crypto::verify(
            self.signature_domain(),
            &self.signature_bytes()?,
            &self.signature,
            &self.header.signer_public_key,
        )
    }

    pub fn encode(&self) -> Result<Vec<u8>> {
        self.verify_id()?;
        crypto::verify(
            self.signature_domain(),
            &self.signature_bytes()?,
            &self.signature,
            &self.header.signer_public_key,
        )?;
        encode_fixed_versioned(MAX_DIRECT_OFFER_SIZE, |encoder| {
            encoder.put_bytes(&self.encode_unsigned()?);
            encoder.put_bytes(&self.offer_id);
            encoder.put_bytes(&self.signature);
            Ok(())
        })
    }

    pub fn decode(input: &[u8]) -> Result<Self> {
        check_input(input)?;
        Self::decode_current(input).or_else(|_| Self::decode_legacy(input))
    }

    fn decode_current(input: &[u8]) -> Result<Self> {
        let mut decoder = Decoder::new(input);
        let offer = Self {
            role_model: DirectOfferRoleModel::decode_current(&mut decoder)?,
            header: SignedObjectHeader::decode_from(&mut decoder)?,
            swap_session_id: decoder.read_array()?,
            offer_setter_settlement_public_key: decoder.read_array()?,
            offered_asset: AssetId::decode_from(&mut decoder)?,
            offered_amount: AssetAmount::decode_from(&mut decoder)?,
            received_asset: AssetId::decode_from(&mut decoder)?,
            received_amount: AssetAmount::decode_from(&mut decoder)?,
            offer_id: decoder.read_array()?,
            signature: decoder.read_array()?,
        };
        decoder.finish()?;
        offer.validate_fields()?;
        offer.verify_id()?;
        crypto::verify(
            offer.signature_domain(),
            &offer.signature_bytes()?,
            &offer.signature,
            &offer.header.signer_public_key,
        )?;
        Ok(offer)
    }

    fn decode_legacy(input: &[u8]) -> Result<Self> {
        let mut decoder = Decoder::new(input);
        let offer = Self {
            role_model: DirectOfferRoleModel::LegacyOfferSetterMaker,
            header: SignedObjectHeader::decode_from(&mut decoder)?,
            swap_session_id: decoder.read_array()?,
            offer_setter_settlement_public_key: decoder.read_array()?,
            offered_asset: AssetId::decode_from(&mut decoder)?,
            offered_amount: AssetAmount::decode_from(&mut decoder)?,
            received_asset: AssetId::decode_from(&mut decoder)?,
            received_amount: AssetAmount::decode_from(&mut decoder)?,
            offer_id: decoder.read_array()?,
            signature: decoder.read_array()?,
        };
        decoder.finish()?;
        offer.validate_fields()?;
        offer.verify_id()?;
        crypto::verify(
            offer.signature_domain(),
            &offer.signature_bytes()?,
            &offer.signature,
            &offer.header.signer_public_key,
        )?;
        Ok(offer)
    }

    fn validate_fields(&self) -> Result<()> {
        self.header.validate()?;
        crypto::validate_public_key(&self.offer_setter_settlement_public_key)?;
        if self.header.pair != MarketPair::HNS_BTC
            || self.swap_session_id == [0; 32]
            || !matches!(self.offered_asset, AssetId::HNS | AssetId::BTC)
            || !matches!(self.received_asset, AssetId::HNS | AssetId::BTC)
            || self.offered_asset == self.received_asset
            || self.offered_amount == AssetAmount::ZERO
            || self.received_amount == AssetAmount::ZERO
            || self.offer_setter_settlement_public_key == self.header.signer_public_key
        {
            return Err(MarketplaceError::Invalid("invalid direct HNS/BTC offer"));
        }
        Ok(())
    }

    fn verify_id(&self) -> Result<()> {
        self.validate_fields()?;
        let expected = crypto::hash(self.id_domain(), &self.encode_unsigned()?);
        if self.offer_id == expected && self.offer_id != [0; 32] {
            Ok(())
        } else {
            Err(MarketplaceError::HashMismatch)
        }
    }

    fn signature_bytes(&self) -> Result<Vec<u8>> {
        let mut bytes = Vec::with_capacity(32 + 256);
        bytes.extend_from_slice(&self.offer_id);
        bytes.extend_from_slice(&self.encode_unsigned()?);
        Ok(bytes)
    }

    fn encode_unsigned(&self) -> Result<Vec<u8>> {
        self.validate_fields()?;
        encode_fixed_versioned(MAX_DIRECT_OFFER_SIZE - 96, |encoder| {
            if self.role_model.is_current() {
                encoder.put_u8(self.role_model as u8);
            }
            self.header.encode_to(encoder);
            encoder.put_bytes(&self.swap_session_id);
            encoder.put_bytes(&self.offer_setter_settlement_public_key);
            self.offered_asset.encode_to(encoder);
            self.offered_amount.encode_to(encoder);
            self.received_asset.encode_to(encoder);
            self.received_amount.encode_to(encoder);
            Ok(())
        })
    }

    const fn id_domain(&self) -> &'static [u8] {
        match self.role_model {
            DirectOfferRoleModel::LegacyOfferSetterMaker => LEGACY_OFFER_ID_DOMAIN,
            DirectOfferRoleModel::OfferSetterTaker => OFFER_ID_DOMAIN,
        }
    }

    const fn signature_domain(&self) -> &'static [u8] {
        match self.role_model {
            DirectOfferRoleModel::LegacyOfferSetterMaker => LEGACY_OFFER_SIGNATURE_DOMAIN,
            DirectOfferRoleModel::OfferSetterTaker => OFFER_SIGNATURE_DOMAIN,
        }
    }
}

/// A signed, monotonic withdrawal of an offer setter's live intent.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct DirectOfferCancellation {
    pub role_model: DirectOfferRoleModel,
    pub header: SignedObjectHeader,
    pub offer_id: [u8; 32],
    pub offer_sequence: u64,
    pub signature: [u8; 64],
}

impl DirectOfferCancellation {
    pub fn sign(&mut self, private_key: &[u8; 32]) -> Result<()> {
        bind_signer(&mut self.header, private_key)?;
        self.signature = crypto::sign(
            self.signature_domain(),
            &self.encode_unsigned()?,
            &self.header.signer_public_key,
            private_key,
        )?;
        Ok(())
    }

    pub fn verify_for_offer(
        &self,
        offer: &DirectOffer,
        expected_network: NetworkBinding,
        now: u64,
    ) -> Result<()> {
        offer.verify_at(expected_network, now)?;
        self.header.validate_at(expected_network, now)?;
        self.verify_signature()?;
        if self.role_model != offer.role_model
            || self.offer_id != offer.offer_id
            || self.offer_sequence != offer.header.sequence
            || self.header.network != offer.header.network
            || self.header.pair != offer.header.pair
            || self.header.signer_public_key != offer.header.signer_public_key
            || self.header.sequence <= offer.header.sequence
            || self.header.created_at < offer.header.created_at
        {
            return Err(MarketplaceError::Invalid(
                "direct-offer cancellation does not bind its offer",
            ));
        }
        Ok(())
    }

    pub fn encode(&self) -> Result<Vec<u8>> {
        self.verify_signature()?;
        encode_signed(&self.encode_unsigned()?, &self.signature)
    }

    pub fn decode(input: &[u8]) -> Result<Self> {
        check_input(input)?;
        Self::decode_current(input).or_else(|_| Self::decode_legacy(input))
    }

    fn decode_current(input: &[u8]) -> Result<Self> {
        let mut decoder = Decoder::new(input);
        let cancellation = Self {
            role_model: DirectOfferRoleModel::decode_current(&mut decoder)?,
            header: SignedObjectHeader::decode_from(&mut decoder)?,
            offer_id: decoder.read_array()?,
            offer_sequence: decoder.read_u64_le()?,
            signature: decoder.read_array()?,
        };
        decoder.finish()?;
        cancellation.validate_fields()?;
        cancellation.verify_signature()?;
        Ok(cancellation)
    }

    fn decode_legacy(input: &[u8]) -> Result<Self> {
        let mut decoder = Decoder::new(input);
        let cancellation = Self {
            role_model: DirectOfferRoleModel::LegacyOfferSetterMaker,
            header: SignedObjectHeader::decode_from(&mut decoder)?,
            offer_id: decoder.read_array()?,
            offer_sequence: decoder.read_u64_le()?,
            signature: decoder.read_array()?,
        };
        decoder.finish()?;
        cancellation.validate_fields()?;
        cancellation.verify_signature()?;
        Ok(cancellation)
    }

    fn validate_fields(&self) -> Result<()> {
        self.header.validate()?;
        if self.offer_id == [0; 32] || self.offer_sequence == 0 {
            Err(MarketplaceError::Invalid(
                "invalid direct-offer cancellation",
            ))
        } else {
            Ok(())
        }
    }

    fn verify_signature(&self) -> Result<()> {
        crypto::verify(
            self.signature_domain(),
            &self.encode_unsigned()?,
            &self.signature,
            &self.header.signer_public_key,
        )
    }

    fn encode_unsigned(&self) -> Result<Vec<u8>> {
        self.validate_fields()?;
        encode_fixed_versioned(MAX_DIRECT_OFFER_SIZE - 64, |encoder| {
            if self.role_model.is_current() {
                encoder.put_u8(self.role_model as u8);
            }
            self.header.encode_to(encoder);
            encoder.put_bytes(&self.offer_id);
            encoder.put_u64_le(self.offer_sequence);
            Ok(())
        })
    }

    const fn signature_domain(&self) -> &'static [u8] {
        match self.role_model {
            DirectOfferRoleModel::LegacyOfferSetterMaker => LEGACY_OFFER_CANCEL_SIGNATURE_DOMAIN,
            DirectOfferRoleModel::OfferSetterTaker => OFFER_CANCEL_SIGNATURE_DOMAIN,
        }
    }
}

/// A responder's signed acceptance of one exact live offer intent.
///
/// The responder becomes the atomic-swap maker. This acceptance binds its
/// maker settlement authority to the offer-scoped session before it sends the
/// separately signed executable swap proposal. The offer setter later verifies
/// and countersigns that proposal as taker.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct DirectOfferAcceptance {
    pub role_model: DirectOfferRoleModel,
    pub header: SignedObjectHeader,
    pub offer_id: [u8; 32],
    pub swap_session_id: [u8; 32],
    pub responding_maker_settlement_public_key: [u8; 33],
    pub signature: [u8; 64],
}

impl DirectOfferAcceptance {
    pub fn sign(&mut self, private_key: &[u8; 32]) -> Result<()> {
        bind_signer(&mut self.header, private_key)?;
        self.signature = crypto::sign(
            self.signature_domain(),
            &self.encode_unsigned()?,
            &self.header.signer_public_key,
            private_key,
        )?;
        Ok(())
    }

    pub fn verify_for_offer(
        &self,
        offer: &DirectOffer,
        expected_network: NetworkBinding,
        now: u64,
    ) -> Result<()> {
        offer.verify_at(expected_network, now)?;
        self.header.validate_at(expected_network, now)?;
        self.verify_signature()?;
        if self.role_model != offer.role_model
            || self.offer_id != offer.offer_id
            || self.swap_session_id != offer.swap_session_id
            || self.header.network != offer.header.network
            || self.header.pair != offer.header.pair
            || self.header.signer_public_key == offer.header.signer_public_key
            || self.header.signer_public_key == offer.offer_setter_settlement_public_key
            || self.responding_maker_settlement_public_key == offer.header.signer_public_key
            || self.responding_maker_settlement_public_key
                == offer.offer_setter_settlement_public_key
            || self.header.created_at < offer.header.created_at
            || self.header.expires_at > offer.header.expires_at
        {
            return Err(MarketplaceError::Invalid(
                "direct-offer acceptance does not bind an eligible live offer",
            ));
        }
        Ok(())
    }

    pub fn encode(&self) -> Result<Vec<u8>> {
        self.verify_signature()?;
        encode_signed(&self.encode_unsigned()?, &self.signature)
    }

    pub fn decode(input: &[u8]) -> Result<Self> {
        check_input(input)?;
        Self::decode_current(input).or_else(|_| Self::decode_legacy(input))
    }

    fn decode_current(input: &[u8]) -> Result<Self> {
        let mut decoder = Decoder::new(input);
        let acceptance = Self {
            role_model: DirectOfferRoleModel::decode_current(&mut decoder)?,
            header: SignedObjectHeader::decode_from(&mut decoder)?,
            offer_id: decoder.read_array()?,
            swap_session_id: decoder.read_array()?,
            responding_maker_settlement_public_key: decoder.read_array()?,
            signature: decoder.read_array()?,
        };
        decoder.finish()?;
        acceptance.validate_fields()?;
        acceptance.verify_signature()?;
        Ok(acceptance)
    }

    fn decode_legacy(input: &[u8]) -> Result<Self> {
        let mut decoder = Decoder::new(input);
        let acceptance = Self {
            role_model: DirectOfferRoleModel::LegacyOfferSetterMaker,
            header: SignedObjectHeader::decode_from(&mut decoder)?,
            offer_id: decoder.read_array()?,
            swap_session_id: decoder.read_array()?,
            responding_maker_settlement_public_key: decoder.read_array()?,
            signature: decoder.read_array()?,
        };
        decoder.finish()?;
        acceptance.validate_fields()?;
        acceptance.verify_signature()?;
        Ok(acceptance)
    }

    fn validate_fields(&self) -> Result<()> {
        self.header.validate()?;
        crypto::validate_public_key(&self.responding_maker_settlement_public_key)?;
        if self.header.pair != MarketPair::HNS_BTC
            || self.offer_id == [0; 32]
            || self.swap_session_id == [0; 32]
            || self.responding_maker_settlement_public_key == self.header.signer_public_key
        {
            Err(MarketplaceError::Invalid("invalid direct-offer acceptance"))
        } else {
            Ok(())
        }
    }

    fn verify_signature(&self) -> Result<()> {
        crypto::verify(
            self.signature_domain(),
            &self.encode_unsigned()?,
            &self.signature,
            &self.header.signer_public_key,
        )
    }

    fn encode_unsigned(&self) -> Result<Vec<u8>> {
        self.validate_fields()?;
        encode_fixed_versioned(MAX_DIRECT_OFFER_SIZE - 64, |encoder| {
            if self.role_model.is_current() {
                encoder.put_u8(self.role_model as u8);
            }
            self.header.encode_to(encoder);
            encoder.put_bytes(&self.offer_id);
            encoder.put_bytes(&self.swap_session_id);
            encoder.put_bytes(&self.responding_maker_settlement_public_key);
            Ok(())
        })
    }

    const fn signature_domain(&self) -> &'static [u8] {
        match self.role_model {
            DirectOfferRoleModel::LegacyOfferSetterMaker => LEGACY_OFFER_TAKE_SIGNATURE_DOMAIN,
            DirectOfferRoleModel::OfferSetterTaker => OFFER_ACCEPT_SIGNATURE_DOMAIN,
        }
    }
}

fn bind_signer(header: &mut SignedObjectHeader, private_key: &[u8; 32]) -> Result<()> {
    let public_key = crypto::public_key(private_key)?;
    if header.signer_public_key != [0; 33] && header.signer_public_key != public_key {
        return Err(MarketplaceError::SigningKeyMismatch);
    }
    header.signer_public_key = public_key;
    header.validate()
}

fn encode_signed(unsigned: &[u8], signature: &[u8; 64]) -> Result<Vec<u8>> {
    encode_fixed_versioned(MAX_DIRECT_OFFER_SIZE, |encoder| {
        encoder.put_bytes(unsigned);
        encoder.put_bytes(signature);
        Ok(())
    })
}

fn check_input(input: &[u8]) -> Result<()> {
    if input.len() > MAX_DIRECT_OFFER_SIZE {
        Err(MarketplaceError::TooLarge {
            actual: input.len(),
            maximum: MAX_DIRECT_OFFER_SIZE,
        })
    } else {
        Ok(())
    }
}

#[cfg(test)]
mod tests {
    use hns_primitives::BlockHash;

    use super::*;
    use crate::{ChainId, CrossChainMessage};

    fn network() -> NetworkBinding {
        NetworkBinding {
            hns_magic: 0x5b6e_c393,
            hns_genesis: BlockHash::new([1; 32]),
            counterchain: ChainId::BITCOIN,
            counterchain_network: 1,
            counterchain_genesis: [2; 32],
        }
    }

    fn header(sequence: u64) -> SignedObjectHeader {
        SignedObjectHeader {
            version: crate::MARKETPLACE_PROTOCOL_VERSION,
            network: network(),
            pair: MarketPair::HNS_BTC,
            signer_public_key: [0; 33],
            sequence,
            created_at: 100,
            expires_at: 200,
        }
    }

    fn offer() -> DirectOffer {
        let mut offer = DirectOffer {
            role_model: DirectOfferRoleModel::OfferSetterTaker,
            header: header(1),
            offer_id: [0; 32],
            swap_session_id: [3; 32],
            offer_setter_settlement_public_key: crypto::public_key(&[9; 32]).unwrap(),
            offered_asset: AssetId::HNS,
            offered_amount: AssetAmount::new(10_000_000),
            received_asset: AssetId::BTC,
            received_amount: AssetAmount::new(2_000),
            signature: [0; 64],
        };
        offer.sign(&[7; 32]).unwrap();
        offer
    }

    #[test]
    fn fixed_offer_acceptance_and_cancellation_bind_exact_terms_without_a_price_policy() {
        let offer = offer();
        assert_eq!(
            DirectOffer::decode(&offer.encode().unwrap()).unwrap(),
            offer
        );
        offer.verify_at(network(), 150).unwrap();

        let mut acceptance = DirectOfferAcceptance {
            role_model: DirectOfferRoleModel::OfferSetterTaker,
            header: header(2),
            offer_id: offer.offer_id,
            swap_session_id: offer.swap_session_id,
            responding_maker_settlement_public_key: crypto::public_key(&[11; 32]).unwrap(),
            signature: [0; 64],
        };
        acceptance.sign(&[10; 32]).unwrap();
        acceptance.verify_for_offer(&offer, network(), 150).unwrap();
        assert_eq!(
            DirectOfferAcceptance::decode(&acceptance.encode().unwrap()).unwrap(),
            acceptance
        );
        let mut wrong_session = acceptance.clone();
        wrong_session.swap_session_id = [4; 32];
        wrong_session.sign(&[10; 32]).unwrap();
        assert!(
            wrong_session
                .verify_for_offer(&offer, network(), 150)
                .is_err()
        );

        let mut cancellation = DirectOfferCancellation {
            role_model: DirectOfferRoleModel::OfferSetterTaker,
            header: header(3),
            offer_id: offer.offer_id,
            offer_sequence: offer.header.sequence,
            signature: [0; 64],
        };
        cancellation.sign(&[7; 32]).unwrap();
        cancellation
            .verify_for_offer(&offer, network(), 150)
            .unwrap();
        assert_eq!(
            DirectOfferCancellation::decode(&cancellation.encode().unwrap()).unwrap(),
            cancellation
        );
    }

    #[test]
    fn legacy_role_bytes_decode_only_as_legacy_and_use_distinct_domains() {
        let current = offer();
        let current_bytes = current.encode().unwrap();

        let mut legacy = current.clone();
        legacy.role_model = DirectOfferRoleModel::LegacyOfferSetterMaker;
        legacy.header.signer_public_key = [0; 33];
        legacy.offer_id = [0; 32];
        legacy.signature = [0; 64];
        legacy.sign(&[7; 32]).unwrap();
        let legacy_bytes = legacy.encode().unwrap();

        assert_ne!(legacy.offer_id, current.offer_id);
        assert_ne!(legacy.signature, current.signature);
        assert_ne!(legacy_bytes, current_bytes);
        assert_eq!(
            DirectOffer::decode(&legacy_bytes).unwrap().role_model,
            DirectOfferRoleModel::LegacyOfferSetterMaker
        );
        assert_eq!(
            DirectOffer::decode(&current_bytes).unwrap().role_model,
            DirectOfferRoleModel::OfferSetterTaker
        );
        assert!(
            CrossChainMessage::DirectOffer(legacy)
                .encode_envelope(1)
                .is_err()
        );
    }
}
