//! Direct fixed-terms HNS/BTC offers.
//!
//! A direct offer has no oracle dependency. It is a signed promise
//! to exchange one exact native amount for another exact native amount.  The
//! live board may display and aggregate those offers as price levels, but that
//! presentation is never settlement authority.

use hns_encoding::Decoder;

use crate::crypto;
use crate::types::encode_fixed_versioned;
use crate::{
    AssetAmount, AssetId, MarketPair, MarketplaceError, NetworkBinding, Result, SignedObjectHeader,
};

pub const MAX_DIRECT_OFFER_SIZE: usize = 8 * 1024;

const OFFER_ID_DOMAIN: &[u8] = b"HNS-DIRECT-OFFER-ID-V1\0";
const OFFER_SIGNATURE_DOMAIN: &[u8] = b"HNS-DIRECT-OFFER-SIGNATURE-V1\0";
const OFFER_CANCEL_SIGNATURE_DOMAIN: &[u8] = b"HNS-DIRECT-OFFER-CANCEL-V1\0";
const OFFER_TAKE_SIGNATURE_DOMAIN: &[u8] = b"HNS-DIRECT-OFFER-TAKE-V1\0";

/// A maker's exact, indivisible HNS/BTC exchange terms.
///
/// `header.signer_public_key` is the maker's long-term marketplace identity.
/// `maker_settlement_public_key` is a distinct per-offer settlement authority
/// that is later bound into the HTLC session. Neither field delegates pricing
/// authority.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct DirectOffer {
    pub header: SignedObjectHeader,
    pub offer_id: [u8; 32],
    pub maker_settlement_public_key: [u8; 33],
    pub offered_asset: AssetId,
    pub offered_amount: AssetAmount,
    pub received_asset: AssetId,
    pub received_amount: AssetAmount,
    pub signature: [u8; 64],
}

impl DirectOffer {
    pub fn refresh_id(&mut self) -> Result<()> {
        self.offer_id = crypto::hash(OFFER_ID_DOMAIN, &self.encode_unsigned()?);
        Ok(())
    }

    /// Sign the fixed terms with the maker's long-term marketplace identity.
    /// The independent settlement key must already have been generated by the
    /// wallet and supplied in `maker_settlement_public_key`.
    pub fn sign(&mut self, private_key: &[u8; 32]) -> Result<()> {
        bind_signer(&mut self.header, private_key)?;
        self.refresh_id()?;
        self.signature = crypto::sign(
            OFFER_SIGNATURE_DOMAIN,
            &self.signature_bytes()?,
            &self.header.signer_public_key,
            private_key,
        )?;
        Ok(())
    }

    pub fn verify_at(&self, expected_network: NetworkBinding, now: u64) -> Result<()> {
        self.header.validate_at(expected_network, now)?;
        self.verify_id()?;
        crypto::verify(
            OFFER_SIGNATURE_DOMAIN,
            &self.signature_bytes()?,
            &self.signature,
            &self.header.signer_public_key,
        )
    }

    pub fn encode(&self) -> Result<Vec<u8>> {
        self.verify_id()?;
        crypto::verify(
            OFFER_SIGNATURE_DOMAIN,
            &self.signature_bytes()?,
            &self.signature,
            &self.header.signer_public_key,
        )?;
        encode_fixed_versioned(MAX_DIRECT_OFFER_SIZE, |encoder| {
            encoder.put_bytes(&self.encode_unsigned()?);
            encoder.put_bytes(&self.offer_id);
            encoder.put_bytes(&self.signature);
            Ok(())
        })
    }

    pub fn decode(input: &[u8]) -> Result<Self> {
        check_input(input)?;
        let mut decoder = Decoder::new(input);
        let offer = Self {
            header: SignedObjectHeader::decode_from(&mut decoder)?,
            maker_settlement_public_key: decoder.read_array()?,
            offered_asset: AssetId::decode_from(&mut decoder)?,
            offered_amount: AssetAmount::decode_from(&mut decoder)?,
            received_asset: AssetId::decode_from(&mut decoder)?,
            received_amount: AssetAmount::decode_from(&mut decoder)?,
            offer_id: decoder.read_array()?,
            signature: decoder.read_array()?,
        };
        decoder.finish()?;
        offer.validate_fields()?;
        offer.verify_id()?;
        crypto::verify(
            OFFER_SIGNATURE_DOMAIN,
            &offer.signature_bytes()?,
            &offer.signature,
            &offer.header.signer_public_key,
        )?;
        Ok(offer)
    }

    fn validate_fields(&self) -> Result<()> {
        self.header.validate()?;
        crypto::validate_public_key(&self.maker_settlement_public_key)?;
        if self.header.pair != MarketPair::HNS_BTC
            || !matches!(self.offered_asset, AssetId::HNS | AssetId::BTC)
            || !matches!(self.received_asset, AssetId::HNS | AssetId::BTC)
            || self.offered_asset == self.received_asset
            || self.offered_amount == AssetAmount::ZERO
            || self.received_amount == AssetAmount::ZERO
            || self.maker_settlement_public_key == self.header.signer_public_key
        {
            return Err(MarketplaceError::Invalid("invalid direct HNS/BTC offer"));
        }
        Ok(())
    }

    fn verify_id(&self) -> Result<()> {
        self.validate_fields()?;
        let expected = crypto::hash(OFFER_ID_DOMAIN, &self.encode_unsigned()?);
        if self.offer_id == expected && self.offer_id != [0; 32] {
            Ok(())
        } else {
            Err(MarketplaceError::HashMismatch)
        }
    }

    fn signature_bytes(&self) -> Result<Vec<u8>> {
        let mut bytes = Vec::with_capacity(32 + 256);
        bytes.extend_from_slice(&self.offer_id);
        bytes.extend_from_slice(&self.encode_unsigned()?);
        Ok(bytes)
    }

    fn encode_unsigned(&self) -> Result<Vec<u8>> {
        self.validate_fields()?;
        encode_fixed_versioned(MAX_DIRECT_OFFER_SIZE - 96, |encoder| {
            self.header.encode_to(encoder);
            encoder.put_bytes(&self.maker_settlement_public_key);
            self.offered_asset.encode_to(encoder);
            self.offered_amount.encode_to(encoder);
            self.received_asset.encode_to(encoder);
            self.received_amount.encode_to(encoder);
            Ok(())
        })
    }
}

/// A signed, monotonic withdrawal of a maker's live offer.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct DirectOfferCancellation {
    pub header: SignedObjectHeader,
    pub offer_id: [u8; 32],
    pub offer_sequence: u64,
    pub signature: [u8; 64],
}

impl DirectOfferCancellation {
    pub fn sign(&mut self, private_key: &[u8; 32]) -> Result<()> {
        bind_signer(&mut self.header, private_key)?;
        self.signature = crypto::sign(
            OFFER_CANCEL_SIGNATURE_DOMAIN,
            &self.encode_unsigned()?,
            &self.header.signer_public_key,
            private_key,
        )?;
        Ok(())
    }

    pub fn verify_for_offer(
        &self,
        offer: &DirectOffer,
        expected_network: NetworkBinding,
        now: u64,
    ) -> Result<()> {
        offer.verify_at(expected_network, now)?;
        self.header.validate_at(expected_network, now)?;
        self.verify_signature()?;
        if self.offer_id != offer.offer_id
            || self.offer_sequence != offer.header.sequence
            || self.header.network != offer.header.network
            || self.header.pair != offer.header.pair
            || self.header.signer_public_key != offer.header.signer_public_key
            || self.header.sequence <= offer.header.sequence
            || self.header.created_at < offer.header.created_at
        {
            return Err(MarketplaceError::Invalid(
                "direct-offer cancellation does not bind its offer",
            ));
        }
        Ok(())
    }

    pub fn encode(&self) -> Result<Vec<u8>> {
        self.verify_signature()?;
        encode_signed(&self.encode_unsigned()?, &self.signature)
    }

    pub fn decode(input: &[u8]) -> Result<Self> {
        check_input(input)?;
        let mut decoder = Decoder::new(input);
        let cancellation = Self {
            header: SignedObjectHeader::decode_from(&mut decoder)?,
            offer_id: decoder.read_array()?,
            offer_sequence: decoder.read_u64_le()?,
            signature: decoder.read_array()?,
        };
        decoder.finish()?;
        cancellation.validate_fields()?;
        cancellation.verify_signature()?;
        Ok(cancellation)
    }

    fn validate_fields(&self) -> Result<()> {
        self.header.validate()?;
        if self.offer_id == [0; 32] || self.offer_sequence == 0 {
            Err(MarketplaceError::Invalid(
                "invalid direct-offer cancellation",
            ))
        } else {
            Ok(())
        }
    }

    fn verify_signature(&self) -> Result<()> {
        crypto::verify(
            OFFER_CANCEL_SIGNATURE_DOMAIN,
            &self.encode_unsigned()?,
            &self.signature,
            &self.header.signer_public_key,
        )
    }

    fn encode_unsigned(&self) -> Result<Vec<u8>> {
        self.validate_fields()?;
        encode_fixed_versioned(MAX_DIRECT_OFFER_SIZE - 64, |encoder| {
            self.header.encode_to(encoder);
            encoder.put_bytes(&self.offer_id);
            encoder.put_u64_le(self.offer_sequence);
            Ok(())
        })
    }
}

/// A taker's request to settle one exact live offer.  This creates no funding
/// authority by itself; the maker must return a separately signed HTLC session
/// proposal that binds this request and the offer's exact terms.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct DirectOfferTake {
    pub header: SignedObjectHeader,
    pub offer_id: [u8; 32],
    pub swap_session_id: [u8; 32],
    pub taker_settlement_public_key: [u8; 33],
    pub signature: [u8; 64],
}

impl DirectOfferTake {
    pub fn sign(&mut self, private_key: &[u8; 32]) -> Result<()> {
        bind_signer(&mut self.header, private_key)?;
        self.signature = crypto::sign(
            OFFER_TAKE_SIGNATURE_DOMAIN,
            &self.encode_unsigned()?,
            &self.header.signer_public_key,
            private_key,
        )?;
        Ok(())
    }

    pub fn verify_for_offer(
        &self,
        offer: &DirectOffer,
        expected_network: NetworkBinding,
        now: u64,
    ) -> Result<()> {
        offer.verify_at(expected_network, now)?;
        self.header.validate_at(expected_network, now)?;
        self.verify_signature()?;
        if self.offer_id != offer.offer_id
            || self.header.network != offer.header.network
            || self.header.pair != offer.header.pair
            || self.header.signer_public_key == offer.header.signer_public_key
            || self.header.signer_public_key == offer.maker_settlement_public_key
            || self.taker_settlement_public_key == offer.header.signer_public_key
            || self.taker_settlement_public_key == offer.maker_settlement_public_key
            || self.header.created_at < offer.header.created_at
            || self.header.expires_at > offer.header.expires_at
        {
            return Err(MarketplaceError::Invalid(
                "direct-offer take does not bind an eligible live offer",
            ));
        }
        Ok(())
    }

    pub fn encode(&self) -> Result<Vec<u8>> {
        self.verify_signature()?;
        encode_signed(&self.encode_unsigned()?, &self.signature)
    }

    pub fn decode(input: &[u8]) -> Result<Self> {
        check_input(input)?;
        let mut decoder = Decoder::new(input);
        let take = Self {
            header: SignedObjectHeader::decode_from(&mut decoder)?,
            offer_id: decoder.read_array()?,
            swap_session_id: decoder.read_array()?,
            taker_settlement_public_key: decoder.read_array()?,
            signature: decoder.read_array()?,
        };
        decoder.finish()?;
        take.validate_fields()?;
        take.verify_signature()?;
        Ok(take)
    }

    fn validate_fields(&self) -> Result<()> {
        self.header.validate()?;
        crypto::validate_public_key(&self.taker_settlement_public_key)?;
        if self.header.pair != MarketPair::HNS_BTC
            || self.offer_id == [0; 32]
            || self.swap_session_id == [0; 32]
            || self.taker_settlement_public_key == self.header.signer_public_key
        {
            Err(MarketplaceError::Invalid("invalid direct-offer take"))
        } else {
            Ok(())
        }
    }

    fn verify_signature(&self) -> Result<()> {
        crypto::verify(
            OFFER_TAKE_SIGNATURE_DOMAIN,
            &self.encode_unsigned()?,
            &self.signature,
            &self.header.signer_public_key,
        )
    }

    fn encode_unsigned(&self) -> Result<Vec<u8>> {
        self.validate_fields()?;
        encode_fixed_versioned(MAX_DIRECT_OFFER_SIZE - 64, |encoder| {
            self.header.encode_to(encoder);
            encoder.put_bytes(&self.offer_id);
            encoder.put_bytes(&self.swap_session_id);
            encoder.put_bytes(&self.taker_settlement_public_key);
            Ok(())
        })
    }
}

fn bind_signer(header: &mut SignedObjectHeader, private_key: &[u8; 32]) -> Result<()> {
    let public_key = crypto::public_key(private_key)?;
    if header.signer_public_key != [0; 33] && header.signer_public_key != public_key {
        return Err(MarketplaceError::SigningKeyMismatch);
    }
    header.signer_public_key = public_key;
    header.validate()
}

fn encode_signed(unsigned: &[u8], signature: &[u8; 64]) -> Result<Vec<u8>> {
    encode_fixed_versioned(MAX_DIRECT_OFFER_SIZE, |encoder| {
        encoder.put_bytes(unsigned);
        encoder.put_bytes(signature);
        Ok(())
    })
}

fn check_input(input: &[u8]) -> Result<()> {
    if input.len() > MAX_DIRECT_OFFER_SIZE {
        Err(MarketplaceError::TooLarge {
            actual: input.len(),
            maximum: MAX_DIRECT_OFFER_SIZE,
        })
    } else {
        Ok(())
    }
}

#[cfg(test)]
mod tests {
    use hns_primitives::BlockHash;

    use super::*;
    use crate::ChainId;

    fn network() -> NetworkBinding {
        NetworkBinding {
            hns_magic: 0x5b6e_c393,
            hns_genesis: BlockHash::new([1; 32]),
            counterchain: ChainId::BITCOIN,
            counterchain_network: 1,
            counterchain_genesis: [2; 32],
        }
    }

    fn header(sequence: u64) -> SignedObjectHeader {
        SignedObjectHeader {
            version: 1,
            network: network(),
            pair: MarketPair::HNS_BTC,
            signer_public_key: [0; 33],
            sequence,
            created_at: 100,
            expires_at: 200,
        }
    }

    fn offer() -> DirectOffer {
        let mut offer = DirectOffer {
            header: header(1),
            offer_id: [0; 32],
            maker_settlement_public_key: crypto::public_key(&[9; 32]).unwrap(),
            offered_asset: AssetId::HNS,
            offered_amount: AssetAmount::new(10_000_000),
            received_asset: AssetId::BTC,
            received_amount: AssetAmount::new(2_000),
            signature: [0; 64],
        };
        offer.sign(&[7; 32]).unwrap();
        offer
    }

    #[test]
    fn fixed_offer_take_and_cancellation_bind_exact_terms_without_a_price_policy() {
        let offer = offer();
        assert_eq!(
            DirectOffer::decode(&offer.encode().unwrap()).unwrap(),
            offer
        );
        offer.verify_at(network(), 150).unwrap();

        let mut take = DirectOfferTake {
            header: header(2),
            offer_id: offer.offer_id,
            swap_session_id: [3; 32],
            taker_settlement_public_key: crypto::public_key(&[11; 32]).unwrap(),
            signature: [0; 64],
        };
        take.sign(&[10; 32]).unwrap();
        take.verify_for_offer(&offer, network(), 150).unwrap();
        assert_eq!(
            DirectOfferTake::decode(&take.encode().unwrap()).unwrap(),
            take
        );

        let mut cancellation = DirectOfferCancellation {
            header: header(3),
            offer_id: offer.offer_id,
            offer_sequence: offer.header.sequence,
            signature: [0; 64],
        };
        cancellation.sign(&[7; 32]).unwrap();
        cancellation
            .verify_for_offer(&offer, network(), 150)
            .unwrap();
        assert_eq!(
            DirectOfferCancellation::decode(&cancellation.encode().unwrap()).unwrap(),
            cancellation
        );
    }
}
