[package]
name = "hns-registry-gen"
description = "Deterministic Denuo Experimental Registry artifact generator"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish = false

[dependencies]
hns-p2p-experimental = { path = "../../crates/hns-p2p-experimental" }

[lints]
workspace = true

