[package]
name = "hns-urkel-proof"
description = "Bounded HSD-compatible Handshake Urkel proof parsing and verification"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
documentation = "https://docs.rs/hns-urkel-proof"
readme = "README.md"
keywords.workspace = true
categories.workspace = true
publish.workspace = true

[dependencies]
blake2.workspace = true
hns-primitives.workspace = true
thiserror.workspace = true

[dev-dependencies]
hex.workspace = true

[lints]
workspace = true
