[package]
name = "hns-p2p-wire"
description = "Runtime-independent standard Handshake P2P framing and packet codecs"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
documentation = "https://docs.rs/hns-p2p-wire"
readme = "README.md"
keywords.workspace = true
categories.workspace = true
publish.workspace = true

[dependencies]
blake2.workspace = true
hns-encoding.workspace = true
hns-header-consensus.workspace = true
hns-mining.workspace = true
hns-primitives.workspace = true
hns-transaction.workspace = true
hns-urkel-proof.workspace = true
thiserror.workspace = true

[dev-dependencies]
hex.workspace = true

[lints]
workspace = true
